# Generated by Django 6.0.5 on 2026-05-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
